version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    container_name: deliveriq-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deliveriq
    ports:
      - "5433:5432"
    volumes:
      - deliveriq_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: deliveriq-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: deliveriq-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  deliveriq_pgdata: